### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.bugvm.llvm.Target

### ISSUE THREAD

**Issue by bugvm** [bugvm/bugvm-idea#1]
[ERROR] Couldn't compile app
java.lang.NoClassDefFoundError: Could not initialize class com.bugvm.llvm.Target
	at com.bugvm.compiler.llvm.DataLayout.<init>(DataLayout.java:35)
	at com.bugvm.compiler.config.Config.build(Config.java:882)
	at com.bugvm.compiler.config.Config.access$5000(Config.java:99)
	at com.bugvm.compiler.config.Config$Builder.build(Config.java:1482)
	at com.bugvm.idea.compilation.BugVmCompileTask.compileForRunConfiguration(BugVmCompileTask.java:210)
	at com.bugvm.idea.compilation.BugVmCompileTask.execute(BugVmCompileTask.java:78)
	at com.intellij.compiler.impl.CompileDriver.executeCompileTasks(CompileDriver.java:627)
	at com.intellij.compiler.impl.CompileDriver.access$400(CompileDriver.java:88)
	at com.intellij.compiler.impl.CompileDriver$3.run(CompileDriver.java:410)
	at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:203)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by bugvm** [comment]
ERROR] Couldn't compile app
java.lang.UnsatisfiedLinkError: Native library for macosx-x86_64 not found
	at com.bugvm.llvm.NativeLibrary.load(NativeLibrary.java:75)
	at com.bugvm.llvm.binding.LLVMJNI.<clinit>(LLVMJNI.java:804)
	at com.bugvm.llvm.binding.LLVM.getLlvmHostTriple(LLVM.java:3103)
	at com.bugvm.llvm.Target.<clinit>(Target.java:36)
	at com.bugvm.compiler.llvm.DataLayout.<init>(DataLayout.java:35)
	at com.bugvm.compiler.config.Config.build(Config.java:882)
	at com.bugvm.compiler.config.Config.access$5000(Config.java:99)
	at com.bugvm.compiler.config.Config$Builder.build(Config.java:1482)
	at com.bugvm.idea.compilation.BugVmCompileTask.compileForRunConfiguration(BugVmCompileTask.java:210)
	at com.bugvm.idea.compilation.BugVmCompileTask.execute(BugVmCompileTask.java:78)
	at com.intellij.compiler.impl.CompileDriver.executeCompileTasks(CompileDriver.java:627)
	at com.intellij.compiler.impl.CompileDriver.access$400(CompileDriver.java:88)
	at com.intellij.compiler.impl.CompileDriver$3.run(CompileDriver.java:410)
	at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:203)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by bugvm** [comment]
When run second time for either device or sim
