### ISSUE TITLE
ios & android cross platform couldn't compile

### ISSUE THREAD

**Issue by bugvm** [bugvm/bugvm-idea#10]
re-import will fix
but why?

**Comment by bugvm** [comment]
same as #7

**Comment by bugvm** [comment]
ERROR] Couldn't compile app
com.bugvm.compiler.CompilerException: Main class com.mycompany.myapp.MyMain not found
	at com.bugvm.compiler.AppCompiler.getRootClasses(AppCompiler.java:269)
	at com.bugvm.compiler.AppCompiler.compile(AppCompiler.java:451)
	at com.bugvm.compiler.AppCompiler.build(AppCompiler.java:768)
	at com.bugvm.idea.compilation.BugVmCompilerThread.doCompile(BugVmCompilerThread.java:60)
	at com.bugvm.idea.compilation.BugVmCompilerThread.run(BugVmCompilerThread.java:66)
