### ISSUE TITLE
libgdx couldn't compile app on first run

### ISSUE THREAD

**Issue by bugvm** [bugvm/bugvm-idea#7]
[ERROR] Couldn't compile app
com.bugvm.compiler.CompilerException: Main class com.mycompany.myapp.Main not found
	at com.bugvm.compiler.AppCompiler.getRootClasses(AppCompiler.java:269)
	at com.bugvm.compiler.AppCompiler.compile(AppCompiler.java:451)
	at com.bugvm.compiler.AppCompiler.build(AppCompiler.java:768)
	at com.bugvm.idea.compilation.BugVmCompilerThread.doCompile(BugVmCompilerThread.java:60)
	at com.bugvm.idea.compilation.BugVmCompilerThread.run(BugVmCompilerThread.java:66)

**Comment by bugvm** [comment]
re-import will fix
but why?
